publisher:
  name: BringYour, Inc.
  address: 5vErPSDb9urcrqmpJ6Jhxne9bEjnCm4diWxNuYphFjRg
  website: https://bringyour.com
  email: support@bringyour.com
  media:
    - purpose: icon
      uri: bringyour.png
app:
  name: BringYour
  address: 5NZ2wvZLWWN9fWxvEm45dFf15iwnRNe3C64a1t4dQQKd
  android_package: com.bringyour.network
  urls:
    license_url: https://bringyour.com/terms
    copyright_url: https://bringyour.com/terms
    privacy_policy_url: https://bringyour.com/privacy
    website: https://bringyour.com
  media:
    - purpose: icon
      uri: icon.png
release:
  address: 7ujSVng5pAXpAqHDK2wpH6R6r6Z8DcPj1H3PqzZdsUuv
  media:
    - purpose: icon
      uri: icon.png
    - purpose: screenshot
      uri: screens/login.png
  files:
    - purpose: install
      uri: release/com.bringyour.network-2024.4.22-outerwerld+1713814676957-8052-solana_dapp-release.apk
  catalog:
    en-US:
      name: BringYour
      short_description: VPN that works just like home
      long_description: Fast and secure internet wherever you want to be, with ultimate control of your data. Take ultimate control of your data between your devices and the cloud. BringYour lets you choose other real devices in the world through which your data travels. Additionally your device can provide security to the network in the background and earn USDC.
      new_in_version: |
        Hot fix to address stopping the VPN when not in use.
        Fixes to address idle timeouts and CPU issues after disconnect. The VPN should now work correctly in always-on mode, including after phone sleep.
        Follow up to the previous release to extend the contract requirement date to April 22.
        Fixes to the client connect algorithm to reduce energy usage and improve speed of connect.
        Fixes to the UI to give better visibility into the connection status.
      saga_features: ''
solana_mobile_dapp_publisher_portal:
  google_store_package: com.bringyour.network
  testing_instructions: ''
