publisher:
  name: BringYour, Inc.
  address: 5vErPSDb9urcrqmpJ6Jhxne9bEjnCm4diWxNuYphFjRg
  website: https://bringyour.com
  email: support@bringyour.com
  media:
    - purpose: icon
      uri: bringyour.png
app:
  name: BringYour
  address: 5NZ2wvZLWWN9fWxvEm45dFf15iwnRNe3C64a1t4dQQKd
  android_package: com.bringyour.network
  urls:
    license_url: https://bringyour.com/terms
    copyright_url: https://bringyour.com/terms
    privacy_policy_url: https://bringyour.com/privacy
    website: https://bringyour.com
  media:
    - purpose: icon
      uri: icon.png
release:
  address: 62rvTvYL4axrSmGkdW7kEk3xm17ciAuGoGPyAd7P1JcM
  media:
    - purpose: icon
      uri: icon.png
    - purpose: screenshot
      uri: screens/login.png
  files:
    - purpose: install
      uri: release/app-solana_dapp-release.apk
  catalog:
    en-US:
      name: BringYour
      short_description: VPN that works just like home
      long_description: Fast and secure internet wherever you want to be, with ultimate control of your data. Take ultimate control of your data between your devices and the cloud. BringYour lets you choose other real devices in the world through which your data travels. Additionally your device can provide security to the network in the background and earn USDC.
      new_in_version: Updates and fixes.
      saga_features: ''
solana_mobile_dapp_publisher_portal:
  google_store_package: com.bringyour.network
  testing_instructions: ''
