name: Build APP

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Keystore
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.APP_SIGNING_KEY }}
        run: |
          mkdir -p $HOME/.android
          echo $ANDROID_KEYSTORE_FILE | base64 --decode > $HOME/.android/debug.keystore
      - name: Build Release apk
        working-directory: app
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ANDROID_KEYSTORE_ALIAS: solana_dapp
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.APP_SIGNING_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.APP_SIGNING_KEY_SOLANA_DAPP_PASSWORD }}
        run: ./gradlew assembleRelease
